export const friendsScheme = [
    {
        id: 1,
        fullId: "#8735",
        name: 'Disket',
        description: "Белый угнетатель",
        note: "Лучший",
        enterDate: "нояб. 24, 2017",
        img: null,
        status: 'online',
        mutual: {
            friends: null,
            groups: 2,
        },
    },
    {
        id: 2,
        fullId: "#5639",
        name: 'Overlord',
        description: null,
        note: "Черножопый",
        enterDate: "янв. 11, 2018",
        img: null,
        status: 'sleep',
        mutual: {
            friends: 2,
            groups: 2,
        },
    },
    {
        id: 3,
        fullId: "#9574",
        name: 'ismaiilka',
        description: null,
        note: null,
        enterDate: "окт. 14, 2020",
        img: null,
        status: 'sleep',
        mutual: {
            friends: 1,
            groups: 2,
        },
    },
    {
        id: 4,
        fullId: "#8573",
        name: 'KillerPyccu',
        description: null,
        note: "Черножопый",
        enterDate: "нояб. 27, 2021",
        img: null,
        status: 'offline',
        mutual: {
            friends: null,
            groups: null,
        },
    },
    {
        id: 5,
        fullId: "#8574",
        name: 'Артем Киселёв БАСО-02-20',
        description: null,
        note: "Черножопый",
        enterDate: "окт. 09, 2020",
        img: null,
        status: 'offline',
        mutual: {
            friends: 1,
            groups: 1,
        },
    },
]